import { CronExpression } from '@nestjs/schedule';

import { APP_CONFIGS } from '../configs/app.config';
import { JobConfig } from '@app/jobs';

export enum SCHEDULED_TASKS {
  CHECK_USER_SUBSCRIPTION_STATUS = 'CHECK_USER_SUBSCRIPTION_STATUS',
  REEL_RECOMMENDATION_SERENDIPITY_DATA_UPDATE = 'REEL_RECOMMENDATION_SERENDIPITY_DATA_UPDATE',
  REEL_RECOMMENDATION_SIMILARITY_DATA_UPDATE = 'REEL_RECOMMENDATION_SIMILARITY_DATA_UPDATE',
  REEL_RECOMMENDATION_STATICAL_DATA_UPDATE = 'REEL_RECOMMENDATION_STATICAL_DATA_UPDATE',
  SUBSCRIPTION_RATE_STATUS_CHECK = 'SUBSCRIPTION_RATE_STATUS_CHECK',
  TRIAL_RATE_STATUS_CHECK = 'TRIAL_RATE_STATUS_CHECK',
  TRIGGER_MANDATE_DEBIT_EXECUTION = 'TRIGGER_MANDATE_DEBIT_EXECUTION',
  TRIGGER_MANDATE_DEBIT_NOTIFICATIONS = 'TRIGGER_MANDATE_DEBIT_NOTIFICATIONS',
  TRIGGER_MANDATE_NOTIFICATION_CHECK = 'TRIGGER_MANDATE_NOTIFICATION_CHECK',
}

export const JobInventory: Record<SCHEDULED_TASKS, JobConfig> = {
  [SCHEDULED_TASKS.CHECK_USER_SUBSCRIPTION_STATUS]: {
    name: SCHEDULED_TASKS.CHECK_USER_SUBSCRIPTION_STATUS,
    repeatOptions: {
      pattern: APP_CONFIGS.PLATFORM.IS_PRODUCTION
        ? CronExpression.EVERY_DAY_AT_MIDNIGHT
        : CronExpression.EVERY_MINUTE,
      tz: 'Asia/Kolkata',
    },
  },
  [SCHEDULED_TASKS.REEL_RECOMMENDATION_SERENDIPITY_DATA_UPDATE]: {
    name: SCHEDULED_TASKS.REEL_RECOMMENDATION_SERENDIPITY_DATA_UPDATE,
    repeatOptions: {
      pattern: CronExpression.EVERY_DAY_AT_3AM,
      tz: 'Asia/Kolkata',
    },
  },
  [SCHEDULED_TASKS.REEL_RECOMMENDATION_SIMILARITY_DATA_UPDATE]: {
    name: SCHEDULED_TASKS.REEL_RECOMMENDATION_SIMILARITY_DATA_UPDATE,
    repeatOptions: {
      pattern: CronExpression.EVERY_DAY_AT_2AM,
      tz: 'Asia/Kolkata',
    },
  },
  [SCHEDULED_TASKS.REEL_RECOMMENDATION_STATICAL_DATA_UPDATE]: {
    name: SCHEDULED_TASKS.REEL_RECOMMENDATION_STATICAL_DATA_UPDATE,
    repeatOptions: {
      pattern: CronExpression.EVERY_DAY_AT_1AM,
      tz: 'Asia/Kolkata',
    },
  },
  [SCHEDULED_TASKS.SUBSCRIPTION_RATE_STATUS_CHECK]: {
    name: SCHEDULED_TASKS.SUBSCRIPTION_RATE_STATUS_CHECK,
    repeatOptions: {
      pattern: CronExpression.EVERY_DAY_AT_10AM,
      tz: 'Asia/Kolkata',
    },
  },
  [SCHEDULED_TASKS.TRIAL_RATE_STATUS_CHECK]: {
    name: SCHEDULED_TASKS.TRIAL_RATE_STATUS_CHECK,
    repeatOptions: {
      pattern: CronExpression.EVERY_5_MINUTES,
      tz: 'Asia/Kolkata',
    },
  },
  [SCHEDULED_TASKS.TRIGGER_MANDATE_DEBIT_EXECUTION]: {
    name: SCHEDULED_TASKS.TRIGGER_MANDATE_DEBIT_EXECUTION,
    repeatOptions: {
      pattern: '0 3-5,10-13 * * *', // From 3-5am and then 10am-1pm
      tz: 'Asia/Kolkata',
    },
  },
  [SCHEDULED_TASKS.TRIGGER_MANDATE_DEBIT_NOTIFICATIONS]: {
    name: SCHEDULED_TASKS.TRIGGER_MANDATE_DEBIT_NOTIFICATIONS,
    repeatOptions: {
      pattern: '0 21-23,0-5,10-12 * * *', // From 9pm-5am and then 10am-12pm
      tz: 'Asia/Kolkata',
    },
  },
  [SCHEDULED_TASKS.TRIGGER_MANDATE_NOTIFICATION_CHECK]: {
    name: SCHEDULED_TASKS.TRIGGER_MANDATE_NOTIFICATION_CHECK,
    repeatOptions: {
      pattern: CronExpression.EVERY_4_HOURS,
      tz: 'Asia/Kolkata',
    },
  },
};
