export enum DDMetric {
  // Ncanto Related Metrics
  NcantoBatchCompleted = 'interactions.batch.completed',
  NcantoBatchSize = 'interactions.batch_size',
  NcantoBlacklistAssetFailure = 'ncanto.blacklist.asset.failure',
  NcantoBlacklistAssetSuccess = 'ncanto.blacklist.asset.success',
  NcantoCreateProfileFailure = 'ncanto.create.profile.failure',
  NcantoCreateProfileSuccess = 'ncanto.create.profile.success',
  NcantoCreateStoreFailure = 'ncanto.create.store.failure',
  NcantoCreateStoreSuccess = 'ncanto.create.store.success',
  NcantoFailureInteractions = 'interactions.processed.failure',
  NcantoGetProfileFailure = 'ncanto.get.profile.failure',
  NcantoGetProfileSuccess = 'ncanto.get.profile.success',
  NcantoGetRecommendationsFailure = 'ncanto.get.recommendations.failure',
  NcantoGetRecommendationsSuccess = 'ncanto.get.recommendations.success',
  NcantoGetStoreFailure = 'ncanto.get.store.failure',
  NcantoGetStoreSuccess = 'ncanto.get.store.success',
  NcantoGetSubscriberFailure = 'ncanto.get.subscriber.failure',
  NcantoGetSubscriberSuccess = 'ncanto.get.subscriber.success',
  NcantoProfileAddFailure = 'ncanto.add.profile.failure',
  NcantoProfileAddSuccess = 'ncanto.add.profile.success',
  NcantoRemoveContentMetadataFailure = 'ncanto.remove.content.metadata.failure',
  NcantoRemoveContentMetadataSuccess = 'ncanto.remove.content.metadata.success',
  NcantoStoreAssetUpdateFailure = 'ncanto.update.asset.failure',
  NcantoStoreAssetUpdateSuccess = 'ncanto.update.asset.success',
  NcantoSubscriberCreationFailure = 'ncanto.create.subscriber.failure',
  NcantoSubscriberCreationSuccess = 'ncanto.create.subscriber.success',
  NcantoSuccessInteractions = 'interactions.processed.success',
  NcantoSuccessRate = 'interactions.success_rate',
  NcantoTotalDroppedInteractions = 'interactions.dropped.total',
  NcantoTotalProcessedInteractions = 'interactions.processed.total',
  NcantoTotalSuccessInteractions = 'interactions.success.total',
  NcantoUpdateSubscriberFailure = 'ncanto.update.subscriber.failure',
  NcantoUpdateSubscriberSuccess = 'ncanto.update.subscriber.success',
}
