/**
 * Centralized Error Codes
 * 
 * Format: DOMAIN_ERROR_TYPE
 * Usage: throw new BadRequestException({ code: ErrorCodes.BOOKING_ALREADY_ACTIVE, message: '...' })
 */
export const ErrorCodes = {
  // Auth Errors (1xxx)
  AUTH_INVALID_TOKEN: 'AUTH_1001',
  AUTH_TOKEN_EXPIRED: 'AUTH_1002',
  AUTH_INVALID_CREDENTIALS: 'AUTH_1003',
  AUTH_USER_NOT_FOUND: 'AUTH_1004',
  AUTH_OTP_EXPIRED: 'AUTH_1005',
  AUTH_OTP_INVALID: 'AUTH_1006',
  AUTH_OTP_NOT_FOUND: 'AUTH_1007',
  AUTH_PHONE_ALREADY_VERIFIED: 'AUTH_1008',

  // User Errors (2xxx)
  USER_NOT_FOUND: 'USER_2001',
  USER_ALREADY_EXISTS: 'USER_2002',
  USER_PHONE_NOT_VERIFIED: 'USER_2003',
  USER_BLOCKED: 'USER_2004',

  // Booking Errors (3xxx)
  BOOKING_NOT_FOUND: 'BOOKING_3001',
  BOOKING_ALREADY_ACTIVE: 'BOOKING_3002',
  BOOKING_INVALID_STATE: 'BOOKING_3003',
  BOOKING_NOT_CANCELLABLE: 'BOOKING_3004',
  BOOKING_INVALID_OTP: 'BOOKING_3005',
  BOOKING_LOCK_FAILED: 'BOOKING_3006',
  BOOKING_ALREADY_ACCEPTED: 'BOOKING_3007',

  // Driver Errors (4xxx)
  DRIVER_NOT_FOUND: 'DRIVER_4001',
  DRIVER_NOT_VERIFIED: 'DRIVER_4002',
  DRIVER_ALREADY_HAS_BOOKING: 'DRIVER_4003',
  DRIVER_NOT_ONLINE: 'DRIVER_4004',
  DRIVER_LOCATION_NOT_FOUND: 'DRIVER_4005',

  // Payment Errors (5xxx)
  PAYMENT_FAILED: 'PAYMENT_5001',
  PAYMENT_INVALID_AMOUNT: 'PAYMENT_5002',
  PAYMENT_REFUND_FAILED: 'PAYMENT_5003',

  // System Errors (9xxx)
  SYSTEM_INTERNAL_ERROR: 'SYS_9001',
  SYSTEM_SERVICE_UNAVAILABLE: 'SYS_9002',
  SYSTEM_RATE_LIMITED: 'SYS_9003',
} as const;

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];

